#!/bin/bash
#functions
function propstr { 
  echo -n 'Property ';
  xprop WM_CLASS | sed 's/.*"\(.*\)", "\(.*\)".*/= "\1,\2" {/g';
  echo '}'
}

function sub {
     ruby -i -pe "gsub($1, \"$2\")" $3
}

function rv {
  gvim --remote-silent $1
}

function fn {
  find . -name $1 
}

function vn {
  find . -name $1 -exec vi {} \;
}

function set_window_title {
  echo -ne "\"\033]0;${1}\007\""
}

function pd { 
  pushd -n ${1:-$PWD} > /dev/null && d 
}

function cd {
  if [[ ${1} =~ ^=[0-9]+ ]]; then
    builtin cd $(dirs -l +${1#=})
  else
    builtin cd "${@}"
  fi
}

